version: '2'
services:
  database:
    image: store/oracle/database-enterprise:12.2.0.1
    container_name: dna-research-database
    volumes:
      - ./db:/var/tmp/scripts
    ports:
      - 1521:1521
    environment:
      - DB_SID=dnadb
