spring:
  application:
    name: dna-research
  jackson:
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/dnadb.localdomain
    username: dna
    password: dna
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    baseline-on-migrate: true
